# TODO: Translation updated at 2022-01-11 21:45

translate english strings:

    # game/scripts/splashscreen.rpy:62
    old "Accessibility Tips: To enable auto-voicing of the text, please first configure the speech synthesis settings (speaker gender, accent, etc.) on your computer according to {a=https://www.renpy.org/doc/html/self_voicing.html#speech-synthesis}these instructions{/a}. Back to the game, you may press the {b}{u}v{/u}{/b} key to switch on auto-voicing.\n\nAdjust the volume of music and sound effects on the {icon=icon-settings} Settings screen.\n\nPress the {b}{u}Esc{/u}{/b} key to access the {icon=icon-grid}Game Menu at any time during the game."
    new "Accessibility Tips: To enable auto-voicing of the text, please first configure the speech synthesis settings (speaker gender, accent, etc.) on your computer according to {a=https://www.renpy.org/doc/html/self_voicing.html#speech-synthesis}these instructions{/a}. Back to the game, you may press the {b}{u}v{/u}{/b} key to switch on auto-voicing.\n\nAdjust the volume of music and sound effects on the {icon=icon-settings} Settings screen.\n\nPress the {b}{u}Esc{/u}{/b} key to access the {icon=icon-grid}Game Menu at any time during the game."

    # game/scripts/splashscreen.rpy:79
    old "This game, {b}Learn to Code RPG{/b}, is currently in beta. \n\nThe current version is v1.5. Save data from v1 might not be compatible with this version. Please start a new game instead of loading from your v1 data if applicable.\n\nIf you notice any bugs or have suggestions about accessibility, the interface, the story, or anything at all, please report them on our {a=https://github.com/freeCodeCamp/LearnToCodeRPG}GitHub repo{/a}. Please always download the latest version of the game from {a=https://freecodecamp.itch.io/learn-to-code-rpg}itch.io{/a} as we continuously update the builds to address your feedback.\n\nIf you are enjoying this game, please {icon=icon-thumbs-up} rate and review us on {a=https://freecodecamp.itch.io/learn-to-code-rpg}itch.io{/a} and {icon=icon-star} star our {a=https://github.com/freeCodeCamp/LearnToCodeRPG}GitHub repo{/a}."
    new "This game, {b}Learn to Code RPG{/b}, is currently in beta. \n\nThe current version is v1.5. Save data from v1 might not be compatible with this version. Please start a new game instead of loading from your v1 data if applicable.\n\nIf you notice any bugs or have suggestions about accessibility, the interface, the story, or anything at all, please report them on our {a=https://github.com/freeCodeCamp/LearnToCodeRPG}GitHub repo{/a}. Please always download the latest version of the game from {a=https://freecodecamp.itch.io/learn-to-code-rpg}itch.io{/a} as we continuously update the builds to address your feedback.\n\nIf you are enjoying this game, please {icon=icon-thumbs-up} rate and review us on {a=https://freecodecamp.itch.io/learn-to-code-rpg}itch.io{/a} and {icon=icon-star} star our {a=https://github.com/freeCodeCamp/LearnToCodeRPG}GitHub repo{/a}."

    # game/scripts/splashscreen.rpy:34
    old "We've released a new version on itch.io that contains bug fixes and feature enhancements. Would you like to download the new version now?"
    new "We've released a new version on itch.io that contains bug fixes and feature enhancements. Would you like to download the new version now?"
